version: "3.0"
services:
  neo:
    image: neo4j:3.1.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./neo4j/data:/data"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/etc/redis.conf"
    command: ["redis-server", "/etc/redis.conf"] 

