kafka:
  image: anoopnair/kafka_alpine:0.9.0.1
  hostname: kafka
  ports:
    - "9092:9092"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.56.102
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka-manager:
  image: sheepkiller/kafka-manager:latest
  ports:
    - "9000:9000"
  environment:
    ZK_HOSTS: "zk:2181"
    APPLICATION_SECRET: letmein
    KM_ARGS: -Djava.net.preferIPv4Stack=true
