instances:
 - corr-02
 - airport-01
 - prolong-mano
 - bibus
 - mission
 - test-02
 - sherbrooke
 - stif
 - test-03
 - nb-corr-05
 - rebroussement
 - map
 - fr-pdl
 - nb-corr-04
 - freqgtfs
 - corr-01
 - passe-minuit-01
 - guichet-unique
 - freqparis
 - itl
 - poitiers
 - test-01
 - boucle-01
 - paysdelaloire
 - saintomer
 - airport
 - tcl
 - passe-minuit-02
 - nb-corr-01
 - mdi
 - nb-corr-03
 - prolong-auto
 - nb-corr-02
 - freqsimple
 - freqgtfs-01
 - tad
 - fr-auv
