# Default values for nfsChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Replace with the NFS Server 
nfsServer: 10.125.2.77
storage:
  shared:
    path: "/container_persistancy/s4h-ml-k8/SharedData/"
    size: "3Ti"
  public:
    path: "/container_persistancy/s4h-ml-k8/RawData"
    size: "3Ti"
  user:
   path: "/container_persistancy/s4h-ml-k8/UserData"
   size: "3Ti"
nfsWeb:
  serviceType:
    type: NodePort
    nodePort:
      port: 32000
    loadBalancer:
      publicIP: null

