---
docker:
  crane:
    list:
      - find . -name crane*\\.y* > .crane.list.txt
  compose:
    list:
      - echo "# docker-compose files" > .dockerfiles.list.txt
      - find . -name docker-compose*\\.y* > .docker-compose.list.txt
  dockerfiles:
    list:
      - echo "# dockerfiles" > .dockerfiles.list.txt
      - find . -name *.dockerfile* >> .dockerfiles.list.txt
      - find . -name *Dockerfile* >> .dockerfiles.list.txt
  images:
  	pull:
		- beniz/deepdetect_${PROCESSOR_COMPUTATION_TYPE}
    - floydhub/dl-docker:${PROCESSOR_COMPUTATION_TYPE}