---
version: '2.1'
services:
  # golang - devzone
  golang:
    image: "${DOCKER_HUB_ACCOUNT}/golang:${GOLANG_VERSION}-alpine3.6"
    build:
      context: "./dockerfiles/golang"
      dockerfile: "golang${GOLANG_VERSION}-alpine.dockerfile"
    container_name: golang-${GOLANG_VERSION}
    volumes_from:
    - data
    expose:
    - 9000
    links:
    - webdis
    - redis
    - postgres
    - mariadb
    - mysql
    - mongodb
    - sphinx
    env_file:
    - "./golang/golang.config.env"
  # php - devzone
  php:
    image: "${DOCKER_HUB_ACCOUNT}/php-fpm:7.0-alpine3.6"
    build:
      context: "./dockerfiles/php"
      dockerfile: "php-7.0-fpm-alpine.dockerfile"
    container_name: "php-7.0-fpm"
    volumes_from:
    - data
    expose:
    - 9000
    links:
    - webdis
    - redis
    - postgres
    - mariadb
    - mysql
    - mongodb
    - sphinx
    env_file:
    - "./php/php.config.env"
