notebook:
  image: jupyter/minimal-notebook
  ports:
    - "8888:8888"
  volumes:
    - ./work:/home/jovyan/work
#   - ./notebook.pem:/home/jovyan/.local/share/jupyter/notebook.pem
# environment:
#   - PASSWORD=YOURPASS
#   - USE_HTTPS=yes
  restart: unless-stopped
