version: '2'

services:
  backuppc-app:
    image: tiredofit/backupp
    container_name: backuppc-app
    volumes:
      - /var/local/data/backuppc/data:/var/lib/backuppc
      - /var/local/data/backuppc/conf/etc/:/etc/backuppc
      - /var/local/data/backuppc/conf/home/:/home/backuppc
      - /var/local/data/backuppc/logs:/www/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=backuppc.example.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=backuppc.example.org
      - LETSENCRYPT_EMAIL=youremail@example.org

      - ZABBIX_HOSTNAME=backuppc-app
     
      - BACKUPPC_ADMIN_USER=backuppc
      - BACKUPPC_ADMIN_PASS=password

      - BACKUPPC_UUID=10000
      - BACKUPPC_GUID=10000
     
      - SMTP_HOST=smtp.example.org
      - SMTP_MAIL_DOMAIN=example.org
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

