kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v1
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: sap.io/nfsprovisioner
            - name: NFS_SERVER
              value: 10.39.240.209
            - name: NFS_PATH
              value: /exports/UserData/
#             value: /container_persistancy/s4h-ml-k8/UserData/
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.39.240.209
            path: /exports/UserData/
