statsd:
  image: vimagick/statsd
  ports:
    - "8125:8125/udp"
    - "8126:8126/tcp"
  links:
    - graphite
  restart: always

graphite:
  image: vimagick/graphite
  ports:
    - "2003:2003"
    - "2004:2004"
    - "7002:7002"
    - "8080:8080"
    - "9001:9001"
  volumes:
    - ./data:/opt/graphite/storage
  restart: always
