version: '2'
services:
  match:
    image: pavlov/match:latest
    ports:
    - 8888:8888
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "gunicorn", "-b", "0.0.0.0:8888", "-w", "4", "server:app"]
    links:
    - elasticsearch
  elasticsearch:
    image: elasticsearch
    ports:
    - 9200:9200
