version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  nginx:
    build: nginx/
    ports:
      - "8085:8085"
    networks:
      - docker_elk
    depends_on:
      - kibana
  alpine:
    build: alpine
    networks:
      - docker_elk
    depends_on:
      - kibana

networks:
  docker_elk:
    driver: bridge
