version: '3'

services:
  spark-hubot:
    build: hubot/
    container_name: spark-hubot
    restart: always
    volumes:
      - ~/Workspace/ck/ops-bot/scripts:/hubot/scripts
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    environment:
      - HUBOT_LOG_LEVEL=debug
      - PORT=8080
      - HUBOT_PORT=8080
      - HUBOT_ADAPTER=spark
      - BOT_NAME=ops-bot
      - HUBOT_NAME=ops-bot
      - HUBOT_SPARK_ACCESS_TOKEN=@token
      - HUBOT_SPARK_ROOMS=@token
      - HUBOT_AUTH_ADMIN=U06LZSRD0
      - REDIS_URL=redis://redis:6379
    links:
      - redis
    command: ./bin/hubot -a spark
    networks:
      - spark-hubot

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro
    command: redis-server --appendonly yes
    networks:
      - spark-hubot

networks:
  spark-hubot:
    driver: bridge
