apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
