version: '2'
services:
  elangapi:
    image: webdevops/php-nginx:alpine-3-php7
    container_name: elangapi
    volumes:
      - .:/app
    environment:
      - WEB_DOCUMENT_INDEX=index.php
      - WEB_DOCUMENT_ROOT=/app/.
      - APPLICATION_PATH=/app
    ports:
      - "3002:80"

  neo4j:
    container_name: neo4j
    image: neo4j:3.2.0
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./vms/neo4j/data:/data
      - ./vms/neo4j/logs:/logs
      - ./vms/neo4j/conf:/conf
