drone:
  image: drone/drone
  ports:
    - "8000:80"
  volumes:
    - ./data:/var/lib/drone
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - REMOTE_DRIVER=gogs
    - REMOTE_CONFIG=http://git.easypi.info:3000/?open=false
    - DEBUG=false
  restart: always

wall:
  image: drone/drone-wall
  ports:
    - "8080:80"
  restart: always
